QuarterlySales/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;

namespace QuarterlySales.Controllers
{
    [Authorize(Roles = "Admin")]

    public class EmployeeController : Controller
    {
        private Repository<Employee> data { get; set; }
        public EmployeeController(SalesContext ctx) => data = new Repository<Employee>(ctx);

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Employee employee)
        {
            // server side checks for remote validation
            string msg = Validate.CheckEmployee(data, employee);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(Employee.DOB), msg);
            }
            msg = Validate.CheckManagerEmployeeMatch(data, employee);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(Employee.ManagerId), msg);
            }

            if (ModelState.IsValid) {
                data.Insert(employee);
                data.Save();
                TempData["message"] = $"Employee {employee.Fullname} added";
                return RedirectToAction("Index", "Home");
            }
            else {
                ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
                return View();
            }
        }
    }
}

QuarterlySales/Controllers/SalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;

namespace QuarterlySales.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private UnitOfWork data { get; set; }
        public SalesController(SalesContext ctx) => data = new UnitOfWork(ctx);

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Sales sales)
        {
            // server side check for remote validation
            string msg = Validate.CheckSales(data, sales);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(sales.EmployeeId), msg);
            }

            if (ModelState.IsValid)
            {
                data.Sales.Insert(sales);
                data.Save();
                TempData["message"] = "Sales added";
                return RedirectToAction("Index", "Home");
            }
            else 
            {
                ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
                return View();
            }
            
        }
    }
}

QuarterlySales/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using QuarterlySales.Models;


namespace QuarterlySales.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private UserManager<User> userManager;
        private RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<User> userMngr,
            RoleManager<IdentityRole> roleMngr)
        {
            userManager = userMngr;
            roleManager = roleMngr;
        }
        public async Task<IActionResult> Index()
        {
            List<User> users = new List<User>();
            foreach (User user in userManager.Users)
            {
                user.RoleNames = await userManager.GetRolesAsync(user);
                users.Add(user);
            }
            UserViewModel model = new UserViewModel
            {
                Users = users,
                Roles = roleManager.Roles
            };
            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result =
                    await userManager.DeleteAsync(user);
                if (!result.Succeeded)
                { // if failed
                    string errorMessage = "";
                    foreach (IdentityError error in result.Errors)
                    {
                        errorMessage += error.Description + " | ";
                    }
                    TempData["message"] = errorMessage;
                }
            }
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole =
                await roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. "
                    + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                User user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Admin"));
            return RedirectToAction("Index");
        }



    }
}

QuarterlySales/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<ul class="nav nav-tabs mt-2 mb-3">
    <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="User" asp-area="Admin">Manage Users</a>
    </li>
</ul>

@RenderBody()

QuarterlySales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @* based on default navbar that comes with MVC template *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* go to action method that clears route segments and then loads home page *@
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Clear">Home</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Sales" asp-action="Add">Add Sales</a>
                            </li>
                        }

                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Employee" asp-action="Add">Add Employee</a>
                                </li>
                            }
                            @inject SignInManager<User> signInManager
                            @if (signInManager.IsSignedIn(User))
                            {
                                // signed-in user - Log Out button and username
                                <li class="nav-item">
                                    <form method="post" asp-action="Logout"
                                          asp-controller="Account" asp-area="">
                                        <input type="submit" value="Log Out"
                                               class="btn btn-primary" />
                                        <span class="text-dark">Welcome, @User.Identity.Name!</span>
                                    </form>
                                </li>
                            }
                            else
                            {
                                // get current action
                                var action = ViewContext.RouteData.Values["action"]?.ToString();

                                // anonymous user - Register link and Log In button
                                <li class="nav-item @Nav.Active("Register", action)">
                                    <a asp-action="Register" asp-controller="Account"
                                       asp-area="" class="nav-link">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Login" asp-controller="Account"
                                       asp-area="" class="btn btn-primary">Log In</a>
                                </li>
                            }

                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="User" asp-area=""
                                       my-mark-area-active>
                                        <span class="fas fa-cog"></span>&nbsp;Manage Users page
                                    </a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData.Keys.Contains("message"))
            {
                <h2 class="bg-light text-center p-2 mb-2">@TempData["message"]</h2>
            }
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>